### ISSUE TITLE
MultiQC report is empty

### ISSUE THREAD

**Issue by matthdsm** [nf-core/demultiplex#64]
### Description of the bug

Successful run yields empty MQC report

**Comment by matthdsm** [comment]
fixed in #63

**Comment by berguner** [comment]
Hi @matthdsm,
I am still getting empty Multiqc reports unfortunately. It was fine when I was using the `fix/bclconvert` branch. I had to start using the master branch because the fix branch was merged and I started getting the empty Multiqc reports. I also ran the pipeline locally with `-profile test,docker` and it didn't even produce a Multiqc report. I pulled the repo to make sure that I am running the latest version (b0a004e) .

**Comment by matthdsm** [comment]
Hi!

Please try running the dev version, the fixes haven’t been merged into main AFAIK.

Matthias

Op 3 jan. 2023 om 17:16 heeft Bekir Ergüner ***@***.***> het volgende geschreven:

﻿

Hi @matthdsm<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmatthdsm&data=05%7C01%7CMatthias.DeSmet%40ugent.be%7Cfc301809ebda4fff087308daeda5d5ee%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C638083593752637489%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XTu42tkPU%2BAhSWEbfITh%2BhSoopk4WAyYOjjZpDsDhwE%3D&reserved=0>,
I am still getting empty Multiqc reports unfortunately. It was fine when I was using the fix/bclconvert branch. I had to start using the master branch because the fix branch was merged and I started getting the empty Multiqc reports. I also ran the pipeline locally with -profile test,docker and it didn't even produce a Multiqc report. I pulled the repo to make sure that I am running the latest version (b0a004e<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnf-core%2Fdemultiplex%2Fcommit%2Fb0a004eb2e79f6fceb9b5d79b91b563b7724ed62&data=05%7C01%7CMatthias.DeSmet%40ugent.be%7Cfc301809ebda4fff087308daeda5d5ee%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C638083593752637489%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kiyoBP2f89I0qshR%2FWTVDh3jSIpTIg%2F1s%2F25MuPJBxs%3D&reserved=0>) .

**Comment by Emiller88** [comment]
This is happening for bclconvert again. I think I haven't dug into it a ton yet.
